# Google Analytics Tracking ID
google_analytics: UA-78267963-2

# Default portfolio post
default_cover: /images/unsplash.jpg
default_post_title: meiqiu

fancybox: true

# scripts
scripts:
  jquery: //cdn.bootcss.com/jquery/3.2.1/jquery.slim.min.js
  tether: //cdn.bootcss.com/tether/1.4.0/js/tether.min.js
  bootstrap: //maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js
  popper: //cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js
  moment: //cdn.bootcss.com/moment.js/2.19.0/moment.min.js
  fancybox: //cdn.bootcss.com/fancybox/3.1.25/jquery.fancybox.min.js
# css
css:
  bootstrap: //maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css
  fontawesome: //cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.min.css
  fancybox: //cdn.bootcss.com/fancybox/3.1.25/jquery.fancybox.min.css
